# Schema for "Saved search type" config entities

search_api_saved_searches.type.*:
  type: config_entity
  label: 'Saved search type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    notification_settings:
      type: sequence
      label: 'Notification plugin settings'
      orderby: key
      sequence:
        type: plugin.plugin_configuration.search_api_saved_searches_notification.[%key]
        label: 'The configuration for a single notification plugin'
    options:
      type: mapping
      label: 'Options'
      mapping:
        displays:
          type: mapping
          label: 'Search displays'
          mapping:
            default:
              type: boolean
              label: 'Whether to exclude (TRUE) or include (FALSE) the selected displays.'
            selected:
              type: sequence
              label: 'The selected displays'
              orderby: value
              sequence:
                type: string
                label: 'A display plugin ID'
        date_field:
          type: sequence
          label: 'Method for determining new results (per index)'
          orderby: key
          sequence:
            type: string
            label: 'The date field to use for this index (or empty to determine via result IDs)'
        description:
          type: text
          label: 'User interface description'
        max_results:
          type: integer
          label: 'Maximum number of new results to report'
        notify_interval:
          type: mapping
          label: 'Notification interval settings'
          mapping:
            customizable:
              type: boolean
              label: 'Whether the user can select the notification interval themselves'
            default_value:
              type: integer
              label: 'The default value to set as the notification interval (in seconds)'
            options:
              type: sequence
              label: 'Options for the "Notification interval" user option (if customizable = TRUE)'
              sequence:
                type: string
                label: 'The options''s label (key is the interval in seconds, or -1 for never)'
        query_limit:
          type: integer
          label: 'Limit to set on the search query for retrieving new results (if method for determining new results is "via result IDs")'
