<?php

/**
 * @file
 * Contains aheadtasks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aheadtasks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aheadtasks module.
    case 'help.page.aheadtasks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Style and form tweaks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function aheadtasks_theme() {
  return [
    'aheadtasks' => [
      'render element' => 'children',
    ],
  ];
}
function aheadtasks_preprocess_node(array &$variables) : void {
  // Theme name: 'example', library name: 'example'. 
  $variables['#attached']['library'][] = 'aheadtasks/aheadtasks';
}
